title: "Feroz Soomro"
description: "Personal site powered by Jekyll and Minimal Mistakes"
url: "https://github.com/ferozsoomro/ferozsoomro.github.io"
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

minimal_mistakes_skin: "default"

seo:
  type: "Person"
  name: "Feroz Soomro"
  description: "Academic homepage of Dr. Feroz Soomro, applied mathematician and educator."

author:
  name: "Feroz Soomro"
  avatar: "/assets/images/profile.jpg"
  bio: "Instructor of Mathematics"
  location: "Blacksburg, VA"
  email: "fsoomro@vt.edu"
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=YOURID"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

# Link to custom CSS file
after_footer_scripts:
  - <link rel="stylesheet" href="/assets/css/custom.css">
